# Generated by Django 6.0.4 on 2026-04-12 17:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(verbose_name='Опубликовано')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('total_likes', models.PositiveBigIntegerField(default=0, verbose_name='Число лайков')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('pk', models.CompositePrimaryKey('video', 'user', blank=True, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('pk', models.CompositePrimaryKey('video', 'quality', blank=True, editable=False, primary_key=True, serialize=False)),
                ('quality', models.CharField(choices=[('HD', '720p'), ('FHD', '1080p'), ('UHD', '4k')], default='HD', verbose_name='Качество')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Файл')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video', verbose_name='Видео')),
            ],
        ),
    ]
