# Generated by Django 6.0.4 on 2026-04-14 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='videos.video', verbose_name='Видео'),
        ),
    ]
